"""Generated by `ckh kernelgen` from "C:\\Users\\openvino-258v002\\AppData\\Local\\Temp\\pytest-of-openvino-258v002\\pytest-34\\test_kernel_prepare_reads_dump0\\ovdump\\foo_123456789__sa.cl".

DERIVED and trustworthy: the entry signature below, and the macro list in jit() -- both read
straight out of the .cm.

GUESS: every value marked `# GUESS from host`. Lifted by regex from
(no host .cpp matched)::Foo123456789SaGenerator, which is C++ that branches on
runtime descriptor state. Treat them as leads, not facts.

MISSING: inputs(). There is no honest way to generate it -- see the module docstring in
src/ckh/kernelgen.py. Until it is written, `ckh bench`/`ckh equiv` on this spec will fail
loudly, which is the intended behaviour; a spec that runs on fabricated data would make a
wrong kernel look correct.

Next: .github/agents/ckh-kernel-onboarder.agent.md picks up from here.
"""
from __future__ import annotations

from ckh.kernel import KernelSpec, Shape

SOURCE = "opencl/tests/foo_123456789__sa.cl"
ENTRY = "foo"


def jit(s: Shape) -> dict:
    """Macros the source references but never defines -- without these it will not compile."""
    return {
        "KERNEL_NAME": ENTRY,

    }


def dispatch(s: Shape):
    """(gws, lws).

    host gws = (not found)
    host lws = (not found)
    Those are C++ expressions over runtime params, not numbers. Resolve them against this
    spec's Shape axes yourself; a wrong dispatch does not fail loudly, it measures garbage.
    """
    raise NotImplementedError("dispatch: translate the host expressions above into Shape terms")


def inputs(s: Shape) -> dict:
    """MUST be deterministic per shape -- a generator that re-randomises between the two
    sides of an A/B once produced 0/96 spurious mismatches that looked exactly like a kernel
    bug. Cache it (see kernels/pa_small_q.py)."""
    raise NotImplementedError("inputs: no honest way to generate this -- see kernel-onboarder")


def outputs(s: Shape) -> dict:
    raise NotImplementedError("outputs: one entry per buffer `compare` should read back")


def args(s: Shape, data: dict, out: dict) -> list:
    """Signature order, straight from the source entry point:


    host argument descriptors:
    #   (not found)
    """
    raise NotImplementedError("args: fill in, in the signature order listed above")


SPEC = KernelSpec(
    name="foo_123456789__sa",
    source=SOURCE,
    prod_source="foo_123456789__sa.cl",
    entry=ENTRY,
    jit=jit,
    dispatch=dispatch,
    args=args,
    inputs=inputs,
    outputs=outputs,
    compare=[],          # buffer names to diff in `ckh equiv`
    reference=None,      # TorchReference or KernelReference -- see kernel-onboarder step 2
    cwd="opencl/tests",
    label_keys=[],
)

DEFAULT_AXES: dict = {}
