"""Generated by ckh.gen_reference from kernels/pending/gemm_pytorch.py.
Reference half only -- jit/dispatch/args/outputs/SPEC need a real CM kernel to exist; that's
kernel-onboarder's job, run after this one.

Shape axes: FIXED: kernels/pending/gemm_pytorch.py's get_inputs()/get_init_inputs() already return concrete values; used as the one DEFAULT_AXES point, unchanged.
Tolerance: matched 'matmul' in Model.forward's source -> real fp summation-order rounding expected.
"""
from __future__ import annotations

import functools

import torch

from ckh.kernel import Shape
from ckh.reference import TorchReference
from kernels.pending.gemm_pytorch import Model


@functools.lru_cache(maxsize=8)
def _inputs_cached(hidden_size, input_size, scaling_factor, x_dim0):
    """Deterministic per shape -- covers the Model instance too, not just its input
    tensor(s): if Model.__init__ draws any weights from randomness, a fresh Model(...) built
    inside compute() would re-randomize on every call. Building it once here, cached
    alongside the input tensor(s), is what keeps this deterministic per shape."""
    torch.manual_seed(0)
    model = Model(input_size=input_size, hidden_size=hidden_size, scaling_factor=scaling_factor)
    x = torch.rand(x_dim0, input_size)
    return {"model": model, "x": x}


def inputs(s: Shape) -> dict:
    return _inputs_cached(s.hidden_size, s.input_size, s.scaling_factor, s.x_dim0)


def _compute(s: Shape, data: dict):
    with torch.no_grad():
        return data["model"](data["x"])


REFERENCE = TorchReference(
    compute=_compute,
    tol=(0.01, 0.01),
    # TODO(kernel-onboarder): no CM kernel exists yet to break and prove this check can fail
    # against -- fill this in for real (run a mutation, confirm `ckh equiv gemm` reports
    # FAIL) once one does. Do not replace this with a plausible-sounding claim.
    non_vacuous="",
)

DEFAULT_AXES = {
    "hidden_size": [8192],
    "input_size": [8192],
    "scaling_factor": [1.5],
    "x_dim0": [1024],
}

# jit/dispatch/args/outputs/SPEC come once a CM kernel exists for this --
# see .claude/agents/kernel-onboarder.md
